#!/bin/sh

# Sparta Global laptop reset script!

echo "Welcome to the Sparta macOS Installer"
echo "-------------------------------------"
echo

# Run Apple Update
fancy_echo "Updating macOS..."
sudo softwareupdate -i -a
green_echo "done."

# Set current directory, so we can change back to it in the scripts.
export LAPTOP_INSTALL_DIR=$(pwd)

source config.sh
source homebrew.sh
source ruby.sh
source node.sh
source macos.sh
source ohmyzsh.sh

echo
green_echo "---------------------- Setup Finished! ----------------------"
green_echo "💃💃               🍺  Done provisioning laptop! 🍺           💃💃"
green_echo "-------------------------------------------------------------"
echo

fancy_echo "Restarting..."
sudo shutdown -r now "Restarting machine"