#!/bin/bash
echo "Cloning laptop repo..."
git clone https://github.com/spartaglobal/laptop.git $HOME/laptop
echo "Running install script..."
cd $HOME/laptop

sudo systemsetup -setcomputersleep 180

echo "Welcome to the Sparta macOS Installer"
echo "-------------------------------------"
echo

source $HOME/laptop/config.sh
source $HOME/laptop/homebrew.sh
source $HOME/laptop/ruby.sh
source $HOME/laptop/node.sh
source $HOME/laptop/macos.sh
source $HOME/laptop/ohmyzsh.sh
