#!/bin/sh
echo "Cloning laptop repo"
git clone https://github.com/spartaglobal/laptop.git $HOME/laptop
cd $HOME/laptop && git checkout v2 #Remove once on master
chmod 777 $HOME/laptop/reset
$HOME/laptop/reset
