#!/bin/sh

# Sparta Global laptop reset script!

echo "Welcome to the Sparta macOS Resetter"
echo "------------------------------------"
echo

source config.sh

fancy_echo "This script will RESET your laptop"
input_echo "Are you sure you want to RESET this laptop? There is no going back! Type yes to continue:"
read continue_confirmed

if ! [ "$continue_confirmed" = "yes" ]
then
   fancy_echo "Reset cancelled. Exiting..."
   exit 0
else
  green_echo "Running reset script..."
  echo
fi

# Set current directory, so we can change back to it in the scripts.
export LAPTOP_INSTALL_DIR=$(pwd)

fancy_echo "Removing User Files..."
rm -rf $HOME/Downloads/*
green_echo "Downloads Cleared"
rm -rf $HOME/Documents/*
green_echo "Documents Cleared"
rm -rf $HOME/Desktop/*
green_echo "Desktop Cleared"
rm -rf $HOME/Pictures/*
green_echo "Pictures Cleared"
rm -rf $HOME/Music/*
green_echo "Music Cleared"
rm -rf $HOME/Movies/*
green_echo "Movies Cleared"
rm -rf $HOME/Public/*
green_echo "Public Cleared"
rm -rf $HOME/Sites/*
green_echo "Sites Cleared"
rm -rf $HOME/.Trash/*
green_echo "Trash Empty"
green_echo "done."

# Delete Chrome History
rm -rf $HOME/Library/Application\ Support/Google/Chrome/Default/History
rm -rf $HOME/Library/Application\ Support/Google/Chrome/Default/History-journal

fancy_echo "Cleaning Safari..."
mv $HOME/Library/Safari $HOME/Desktop/Safari-`date +%Y%m%d%H%M%S`
echo $passwd | sudo -S -k rm -Rf $HOME/Library/Caches/Apple\ -\ Safari\ -\ Safari\ Extensions\ Gallery
echo $passwd | sudo -S -k rm -Rf $HOME/Library/Caches/Metadata/Safari
echo $passwd | sudo -S -k rm -Rf $HOME/Library/Caches/com.apple.Safari
echo $passwd | sudo -S -k rm -Rf $HOME/Library/Caches/com.apple.WebKit.PluginProcess
echo $passwd | sudo -S -k rm -Rf $HOME/Library/Cookies/Cookies.binarycookies
echo $passwd | sudo -S -k rm -Rf $HOME/Library/Preferences/Apple\ -\ Safari\ -\ Safari\ Extensions\ Gallery
echo $passwd | sudo -S -k rm -Rf $HOME/Library/Preferences/com.apple.Safari.LSSharedFileList.plist
echo $passwd | sudo -S -k rm -Rf $HOME/Library/Preferences/com.apple.Safari.RSS.plist
echo $passwd | sudo -S -k rm -Rf $HOME/Library/Preferences/com.apple.Safari.plist
echo $passwd | sudo -S -k rm -Rf $HOME/Library/Preferences/com.apple.WebFoundation.plist
echo $passwd | sudo -S -k rm -Rf $HOME/Library/Preferences/com.apple.WebKit.PluginHost.plist
echo $passwd | sudo -S -k rm -Rf $HOME/Library/Preferences/com.apple.WebKit.PluginProcess.plist
echo $passwd | sudo -S -k rm -Rf $HOME/Library/PubSub/Database
echo $passwd | sudo -S -k rm -Rf $HOME/Library/Saved\ Application\ State/com.apple.Safari.savedState
green_echo "done."

fancy_echo "Removing homebrew cask apps..."
brew cask uninstall --force $(brew cask list)
brew cask zap --force $(brew cask list)
brew cask cleanup
green_echo "done."

fancy_echo "Removing homebrew packages..."
brew remove --force $(brew list)
brew cleanup
brew prune
green_echo "done."

fancy_echo "Clearing macOS caches..."
echo $passwd | sudo -S -k rm -rf /Library/Caches/*
echo $passwd | sudo -S -k rm -rf $HOME/Library/Caches/*
green_echo "done."

fancy_echo "Clearing dotfiles..."
rm -rf $HOME/.*
green_echo "done."

# Run setup scripts
source homebrew.sh
source ruby.sh
source dotfiles.sh
source node.sh
source vim.sh # Must be sourced after dotfiles.sh
source macos.sh

# Run Apple Update
fancy_echo "Updating macOS..."
echo $passwd | sudo -S -k softwareupdate -i -a
green_echo "done."

# Run tests
source tests.sh

echo
green_echo "---------------------- Setup Finished! ----------------------"
green_echo "💃💃             🍺  Done reprovisioning laptop! 🍺           💃💃"
green_echo "-------------------------------------------------------------"
echo

sleep 5


fancy_echo "Don't forget to check the output of the unit tests."
input_echo "Do you want to restart the machine now? (type 'yes'): "
read restart_confirmed

if ! [ "$restart_confirmed" = "yes" ]
then
   fancy_echo "All done!"
   exit 0
else
  fancy_echo "Restarting..."
  echo $passwd | sudo -S -k shutdown -r now "Restarting machine"
  unset passwd
fi
