#!/bin/sh

# Sparta Global laptop reset script!

echo "Welcome to the Sparta macOS Installer"
echo "-------------------------------------"
echo

# Set current directory, so we can change back to it in the scripts.
export LAPTOP_INSTALL_DIR=$(pwd)

source $LAPTOP_INSTALL_DIR/src/config.sh
source $LAPTOP_INSTALL_DIR/src/homebrew.sh
source $LAPTOP_INSTALL_DIR/src/ruby.sh
source $LAPTOP_INSTALL_DIR/src/node.sh
source $LAPTOP_INSTALL_DIR/src/macos.sh
source $LAPTOP_INSTALL_DIR/src/ohmyzsh.sh

# Run Apple Update
fancy_echo "Updating macOS..."
sudo softwareupdate -i -a
green_echo "done."

echo
green_echo "---------------------- Setup Finished! ----------------------"
green_echo "💃💃               🍺  Done provisioning laptop! 🍺           💃💃"
green_echo "-------------------------------------------------------------"
echo

fancy_echo "Restarting..."
sudo shutdown -r now "Restarting machine"