#!/bin/sh

# Sparta Global laptop reset script!

echo "Welcome to the Sparta macOS Resetter"
echo "------------------------------------"
echo

source ../src/config.sh

fancy_echo "This script will RESET your laptop"
input_echo "Are you sure you want to RESET this laptop? There is no going back! Type yes to continue:"
read continue_confirmed

if ! [ "$continue_confirmed" = "yes" ]
then
   fancy_echo "Reset cancelled. Exiting..."
   exit 0
else
  green_echo "Running reset script..."
  echo
fi

# Set current directory, so we can change back to it in the scripts.
export LAPTOP_INSTALL_DIR=$(pwd)

fancy_echo "Removing User Files..."
rm -rf $HOME/Downloads/*
green_echo "Downloads Cleared"
rm -rf $HOME/Documents/*
green_echo "Documents Cleared"
rm -rf $HOME/Desktop/*
green_echo "Desktop Cleared"
rm -rf $HOME/Pictures/*
green_echo "Pictures Cleared"
rm -rf $HOME/Music/*
green_echo "Music Cleared"
rm -rf $HOME/Movies/*
green_echo "Movies Cleared"
rm -rf $HOME/Public/*
green_echo "Public Cleared"
rm -rf $HOME/Sites/*
green_echo "Sites Cleared"
rm -rf $HOME/.Trash/*
green_echo "Trash Empty"
rm -rf $HOME/.ssh/*
green_echo "SSH Empty"
green_echo "done."

# Unset github in OSX Keychain
echo "host=github.com\nprovider=https" | git credential-osxkeychain erase

# Delete Chrome History
rm -rf $HOME/Library/Application\ Support/Google/Chrome/Default/History
rm -rf $HOME/Library/Application\ Support/Google/Chrome/Default/History-journal

fancy_echo "Cleaning Safari..."
mv $HOME/Library/Safari $HOME/Desktop/Safari-`date +%Y%m%d%H%M%S`
sudo rm -Rf $HOME/Library/Caches/Apple\ -\ Safari\ -\ Safari\ Extensions\ Gallery
sudo rm -Rf $HOME/Library/Caches/Metadata/Safari
sudo rm -Rf $HOME/Library/Caches/com.apple.Safari
sudo rm -Rf $HOME/Library/Caches/com.apple.WebKit.PluginProcess
sudo rm -Rf $HOME/Library/Cookies/Cookies.binarycookies
sudo rm -Rf $HOME/Library/Preferences/Apple\ -\ Safari\ -\ Safari\ Extensions\ Gallery
sudo rm -Rf $HOME/Library/Preferences/com.apple.Safari.LSSharedFileList.plist
sudo rm -Rf $HOME/Library/Preferences/com.apple.Safari.RSS.plist
sudo rm -Rf $HOME/Library/Preferences/com.apple.Safari.plist
sudo rm -Rf $HOME/Library/Preferences/com.apple.WebFoundation.plist
sudo rm -Rf $HOME/Library/Preferences/com.apple.WebKit.PluginHost.plist
sudo rm -Rf $HOME/Library/Preferences/com.apple.WebKit.PluginProcess.plist
sudo rm -Rf $HOME/Library/PubSub/Database
sudo rm -Rf $HOME/Library/Saved\ Application\ State/com.apple.Safari.savedState
green_echo "done."

fancy_echo "Removing homebrew cask apps..."
brew cask zap --force $(brew cask list)
brew cask uninstall --force $(brew cask list)
brew cask cleanup
green_echo "done."

fancy_echo "Removing homebrew packages..."
brew remove --force $(brew list)
brew cleanup
brew prune
green_echo "done."

fancy_echo "Clearing macOS caches..."
sudo rm -rf /Library/Caches/*
sudo rm -rf $HOME/Library/Caches/*
green_echo "done."

fancy_echo "Clearing dotfiles..."
rm -rf $HOME/.*
green_echo "done."

cd $HOME/laptop
echo "Running install script..."
$HOME/laptop/install